### ISSUE TITLE
Add CI for MacOS

### ISSUE THREAD

**Issue by edouard-lopez** [pure-fish/pure#294]
### Actual

Previous job is failing with `3.5.1` with:

```yml
  test-macos:
    name: Test on fish on MacOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Fish
        run: brew install fish
      - name: Install Fisher > Fishtape > Pure
        run: curl -sL https://git.io/fisher | source && fisher install jorgebucaran/fisher jorgebucaran/fishtape ./
        shell: fish {0}
      - name: Test Pure
        run: fishtape tests/*.test.fish
        shell: fish {0}
```

### Expected 

To have successful CI job for MacOS and latest Fish version
